### PR TITLE
Update fac10 photo

### PR DESCRIPTION
**Pull request by Samatar26**
I've updated the website to show the current FAC10's group picture.
Relates to issue #412

### CODE REVIEW

**Comment by esraajb** [comment]
I think we should first discuss that before you make a PR. Before FAC10 there was only only one cohort running, in London. Now, there are two cohorts running, one in Naz and one in Lon.

**Comment by sohilpandya** [comment]
@esraajb we can put the photo for Nazareth in the Naz page - http://www.foundersandcoders.com/programme/course-information/nazareth and the London Photo in the London page. 

It's just that the Home page needs something as well, unfortunately I don't see all of FAC London and FAC Nazareth coming together for a photo and my photoshop skills aren't so great that I can make us all appear next to each other. 

Have you thought about alternative images that we can put up on the Landing page of the site? 

What if we replace the top landing image with London and the bottom image with Nazareth?

**Comment by bo-bok** [comment]
> What if we replace the top landing image with London and the bottom image with Nazareth?

@sohilpandya The current top image works really well as a landing page image (people working, smiling, natural picture etc) and is better as conveying what we do than a group shot. 

@esraajb I think there's a bigger discussion to be had around how the site is structured/ how we present information now that there's more than one location. As we grow, is it feasible to have every cohorts image on the homepage? The homepage risks becoming a gallery...

**Comment by esraajb** [comment]
I suggest that in the meantime we put a slideshow with two images

**Comment by Samatar26** [comment]
@esraajb I agree with the slideshow/transition, think that's a cool idea. I also remember this tweet, but unfortunately the image quality is subpar.
image

**Comment by sohilpandya** [comment]
@Samatar26 how long do you estimate it would it take for us to implement a slide/transition?

**Comment by Samatar26** [comment]
@sohilpandya Sorry I've just seen this now, didn't see the email. Shouldn't take too long, (<day?). Do you know where the Nazareth cohort pictures are?

**Comment by sohilpandya** [comment]
I've approved this PR. 

@esraajb there are two things that need to happen
1. please create an issue to get the Naz cohort on the front page alongside FAC London
  - Stating that we need to create a transition of some kind between the two images
  - We also need to change the image on this page https://foundersandcoders.com/programme/course-information/nazareth 
  - assign it to Samatar and I'm sure he'll be happy to take a look at it. 
2. Please link us to the high-resolution photo of the whole cohort in Naz

@esraajb is there anyone from Nazareth who is involved in the website maintenance? Might be worth asking them to do these chores rather than you.

**Comment by esraajb** [comment]
@sohilpandya @bo-bok I can't understand the point behind approving this PR.
We agreed that we want to have a slideshow with both cohorts.

I suggest to close this PR and make a new one with a slideshow.

**Comment by esraajb** [comment]
@mattlub is involved in the website maintenance, @Samatar26 feel free to contact him if you need anything

**Comment by sohilpandya** [comment]
@esraajb I'd ❤️for us to make that happen as you can see I did describe the steps that need to be taken for it to happen. 

@mattlub can you please liaise with @Samatar26 and provide the high res photo of the whole group in Nazareth. 

@esraajb please liaise with @bo-bok and update the related issue.

**Comment by bo-bok** [comment]
@esraajb the slideshow solution was proposed 10 days ago and as FAC10/ FACN1 is in week 11, I'm still happy to approve this PR. 

That way the site can be updated (as it should have been two months ago) temporarily and as soon as a new issue is opened and responded to for the slideshow, it can be replaced. Does that sound fair?

**Comment by mattlub** [comment]
@Samatar26 I've just made a pull request providing the high res image of nazareth (#424)

**Comment by esraajb** [comment]
@bo-bok I dont think its fair as you are going to upload FAC10 photo and just ignore FACN1, why do you think its fair? 

#412 this issue should be modified to 'update photo in the landing pages with the current cohortS'
@sohilpandya why do I need to create a new issue while an existing(but not well written) one is already there?

I think we agree that this pr DOES NOT solve the problem correctly, as to that, it should not be approved.

**Comment by bo-bok** [comment]
@esraajb 

_short version:_
Merging this PR does not ignore FACN1. I'm suggesting that the site be updated with an up-to-date picture whilst the work for a slideshow is carried out. You've raised a good point and **I invite you to raise a corresponding issue**. The work to resolve my issue has been completed (as was ready before you raised your concerns) and **I still think it's appropriate to merge it as a temporary improvement.**


_longer version:_
**Why should you be raising a new issue?** 
Apologies if my issue was poorly worded, but _you should still be raising a new issue because our issues are different_. This issue is to replace the current homepage image (which is of FAC9) to one of FAC10. Your issue is to add FACN1's photo to the homepage and if you open a new issue the work will be done.

_sustainability:_
As I said previously, based on the reaction to this issue, I think **there's a bigger discussion to be had around the way the website is structured/designed now that there is more than one location so that all cohorts are properly represented and there are some guidelines so that we can make changes to the site quickly/easily. This could be worked on as a proposal for a business meeting.** 

The current website/landing page is structured for one location, adding an image does not address the core issue and isn't a sustainable approach as FAC opens more international chapters. Asides from future-proofing, this conversation should be have so we can arrive at a more elegant solution than a slideshow for two images (having it on a timer would be a terrible user experience and [users rarely interact with slideshows](https://www.newfangled.com/beware-homepage-slideshow)). I believe we can do better, but I agree it's a good temporary solution and invite you to raise an issue for it.

**Pull request merged**
