### PR TITLE
Change text in the apply section

### LINKED ISSUE #369: Update Apply section to specify vanilla javascript
i.e. skip over Bootstrap & jQuery in Free Code Camp

https://github.com/foundersandcoders/selection-criteria/issues/7

### PR DESCRIPTION
**Pull request by RhodesPeter**
I have changed the text in the apply section so that people who are applying know to skip over the jQuery and Bootstrap sections in Free Code Camp. 

Fixes #369 and directly relates to [this issue](https://github.com/foundersandcoders/selection-criteria/issues/7)

### CODE REVIEW

**Comment by RhodesPeter** [comment]
@njsfield if you merge this please can you show me how you do the Harp compiling? :)

**Comment by jsms90** [comment]
@RhodesPeter @njsfield Please could we get this merged in asap so that people know to avoid frameworks as early as possible? :+1:

**Comment by esraajb** [comment]
ugh.
i didnt notice this PR and made a new one about the same issue.
ill try to fix the merge conflict in here.

**Comment by esraajb** [comment]
I think it's fine now.
Ill close my PR

**Comment by rebeccaradding** [comment]
@RhodesPeter is this PR still open?

**Comment by RhodesPeter** [comment]
Hi @rebeccaradding, sorry I thought this had been merged a while ago. I have looked at the website and can see that it is now outdated so I will close this PR.

**Pull request closed without merging**
