### PR TITLE
Delete press

### LINKED ISSUE #442: Remove press links from "Our Story"
Press links are now located in location-specific course information pages and can be removed from "Our Story."

### PR DESCRIPTION
**Pull request by rebeccaradding**
Fixes #442

### CODE REVIEW

**Comment by rebeccaradding** [comment]
@esraajb would you mind making these changes?

**Comment by esraajb** [comment]
@jsms90 removed from the about section, did not find it anywhere else.

**Comment by rebeccaradding** [comment]
@sofer do you want me to add the CAST video link as well? https://github.com/foundersandcoders/our-site/issues/381

**Comment by rebeccaradding** [comment]
@esraajb any chance you'd be willing to merge these changes?

**Pull request closed without merging**
